name : Basic Expression And Contest Objects

on : workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps :
      - name: Output Context data
        run: echo "${{ toJSON(github) }}"
        # ${{toJSON(github)}} -> Expression
        # From above expression github -> Contest Objects