name : Basic Expression And Contest Objects

on : workflow_dispatch

jobs :
  info:
    runs-on : windows-latest
    steps :
      - name : Expression And Contest Objects
        run : echo "${{toJSON(github)}}"
        # ${{toJSON(github)}} -> Expression
        # From above expression github -> Contest Objects