name : Caching Dependencies
on :
  push :
    branches :
      - master
  workflow_dispatch:

jobs :
  build:
    runs-on : windows-latest
    steps :
      - name : Get The Code
        uses : actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-

      - name : Setup Java
        uses : actions/setup-java@v3
        with :
          java-version : '17'
          distribution : 'temurin'

      - name : Install dependencies
        run : mvn dependency:resolve

  test:
    needs : build
    runs-on : windows-latest
    steps :
      - name : Get The Code
        uses : actions/checkout@v3

      - name: ReStore Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Execute Tese cases
        run: mvn test -Dmaven.repo.local=$RUNNER_WORKSPACE/.m2/repository

      - name : Upload the result report
        uses : actions/upload-artifact@v3
        with :
          name : Reportfile
          path : |
              TestReport
  deploy:
    needs : test
    runs-on : windows-latest
    steps :
      - name : Download the report
        uses : actions/download-artifact@v3
        with :
          name : Reportfile

      - name : Check Report folder
        run : dir

      - name : Closing Execution
        run : echo "Closing The Execution"