name: First_Workflow
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest
    steps :
      - name: Download The Code From Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'

      - name : Install All Dependencies from MVN Command
        run : mvn clean install -DskipTests # -DskipTests which install dependencies by ignoring TC.

      - name : In order to run testcases
        run : mvn clean test # mvn clean install can also be used.
